server.port=9090
server.servlet.context-path=/

spring.datasource.url=jdbc:mysql://localhost:3306/SkillFest
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=INFO
logging.level.com.cibertec.SkillsFest=DEBUG

github.api.token=${GITHUB_TOKEN:}
github.api.baseurl=https://api.github.com

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

server.error.include-message=always
server.error.include-binding-errors=always
api.security.token.secret=NDQ1ZjQ2N2Q1YjRlNTQ1YTUyNGM1NDUyNTY1ZDRjNGU1YTViNGU0ZDQ4NTM1NjRkNTI1ZjRmNTQ1MzRjNGE1ZA==