server.port=${PORT:9090}
server.servlet.context-path=/

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/SkillFest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:mysql}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.root=INFO
logging.level.com.cibertec.SkillsFest=DEBUG

github.api.token=${GITHUB_TOKEN:}
github.api.baseurl=https://api.github.com

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

server.error.include-message=always
server.error.include-binding-errors=always

api.security.token.secret=${JWT_SECRET:NDQ1ZjQ2N2Q1YjRlNTQ1YTUyNGM1NDUyNTY1ZDRjNGU1YTViNGU0ZDQ4NTM1NjRkNTI1ZjRmNTQ1MzRjNGE1ZA==}